config/routes.rb
Rails.application.routes.draw do
  root to: "restaurants#index"

  resource :new_restaurant_searches, only: [:show, :create]
  resources :restaurants, only: [:new, :index, :create]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meat.rb
class Meat < ApplicationRecord
  has_many :restaurant_meats
  has_many :restaurants, through: :restaurant_meats
end

app/models/new_restaurant_search.rb
require "yelp"

class NewRestaurantSearch
  include ActiveModel::Model

  attr_accessor :query, :location

  def initialize(attributes = {})
    super
    @search_service = YelpService
  end

  def results
    if has_query?
      search.map do |result|
        OpenStruct.new(result)
      end
    end
  end

  private

  def has_query?
    query.present? && location.present?
  end

  def search_query
    { query: query, location: location }
  end

  def search
    @search_service.search(search_query)
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :restaurant_sources
  has_many :sources, through: :restaurant_sources

  has_many :restaurant_meats
  has_many :meats, through: :restaurant_meats
  validates :name, :api_id, :display_address,
            :phone, :coordinate, presence: true
end

app/models/restaurant_meat.rb
class RestaurantMeat < ApplicationRecord
  belongs_to :meat
  belongs_to :restaurant
end

app/models/restaurant_source.rb
class RestaurantSource < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :source
end

app/models/source.rb
class Source < ApplicationRecord
  has_many :restaurant_sources
  has_many :restaurants, through: :restaurant_sources
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  validates :admin, presence: true
end

app/models/yelp_service.rb
class YelpService
  DEFAULT_LOCATION_DISTANCE = 10_000

  attr_reader :query, :location

  def initialize(query)
    @query = query[:query]
    @location = query[:location]
  end

  def self.search(query)
    new(query).search
  end

  def search
    search_response.businesses.map do |business|
      parse(business)
    end
  end

  private

  def search_response
    client.search(location, search_params, locale)
  end

  def search_params
    {
      term: query,
      category_filter: category,
      limit: 20,
      sort: 1
    }
  end

  def parse(business)
    {
      name: business.name,
      api_id: business.id,
      display_address: business.location.display_address,
      coordinate: {
        latitude: business.location.coordinate.latitude,
        longitude: business.location.coordinate.longitude
      },
      phone: business.phone
    }
  end

  def client
    Yelp::Client.new(consumer_key: ENV.fetch("YELP_CONSUMER_KEY"),
                     consumer_secret: ENV.fetch("YELP_CONSUMER_SECRET"),
                     token: ENV.fetch("YELP_TOKEN"),
                     token_secret: ENV.fetch("YELP_TOKEN_SECRET")
                    )
  end

  def locale
    { lang: "en" }
  end

  def category
    "restaurants"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/new_restaurant_searches_controller.rb
class NewRestaurantSearchesController < ApplicationController
  def show
    @new_restaurant_search = NewRestaurantSearch.new(restaurant_search_params)
    @results = results
  end

  def create
    redirect_to new_restaurant_searches_path(new_restaurant_search_params)
  end

  private

  def results
    @new_restaurant_search.results
  end

  def restaurant_search_params
    params.permit(:query, :location)
  end

  def new_restaurant_search_params
    params.require(:new_restaurant_search).permit(:query, :location)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @new_restaurant = new_restaurant
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = build_restaurant
    if @restaurant.save
      flash[:notice] = "Restaruant added!"
    else
      flash[:error] = "Error in adding restaruant!"
    end
    redirect_to root_path
  end

  private

  def build_restaurant
    Restaurant.new(restaurant_params)
  end

  def new_restaurant
    OpenStruct.new(new_restaurant_params)
  end

  def restaurant_params
    params.require(:restaurant).permit!
  end

  def new_restaurant_params
    params.require(:result).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <% if signed_in? %>
    Signed in as: <%= current_user.email %>
  <%= button_to 'Sign out', sign_out_path, method: :delete %>
<% else %>
  <%= link_to 'Sign in', sign_in_path %>
<% end %>

<div id="flash">
  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>
</div>

  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/new_restaurant_searches/show.html.erb
<%= form_for @new_restaurant_search, class: "new-restaurant-searches-form" do |form| %>
  <fieldset>
    <%= form.label :query %>
    <%= form.text_field :query %>
    <%= form.label :location %>
    <%= form.text_field :location %>
    <%= form.submit "Search" %>
  </fieldset>
<% end %>

<ul>
  <% if @results %>
    <% @results.each do |result| %>
      <li class="new-restaurant">
        <p class="title">  <%= result.name %>
      <%= link_to 'Add restaurant', new_restaurant_path(result: result.to_h)  %>
        </p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/restaurants/_restaurant.html.erb
<hr>
<div class="list-display">
  <p><%= restaurant.name  %></h4>
  <ul class="meats">
    Meats
    <% restaurant.meats.each do |meat| %>
      <li><%= meat.name %></li>
    <% end %>
  </ul>
  <ul class="sources">
  Sources
    <% restaurant.sources.each do |source| %>
      <li><%= source.name %></li>
    <% end %>
  </ul>
</div>

app/views/restaurants/index.html.erb
<ul class="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%= render 'restaurant', restaurant: restaurant %>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>New GOODmEATS Restaurant</h1>
<h2> <%= @new_restaurant.name %> </h2>
<p class="new-restaurant-address"><%= @new_restaurant.display_address.join(' ')  %></p>
<%= simple_form_for @restaurant do |form| %>
  <%= form.association :sources, label_method: :name, value_method: :id %>
  <%= form.association :meats, label_method: :name, value_method: :id %>
  <%= form.hidden_field :api_id, :value => @new_restaurant.api_id %>
  <%= form.hidden_field :name, :value => @new_restaurant.name %>
  <%= form.hidden_field :phone, :value => @new_restaurant.phone %>
  <%= form.hidden_field :coordinate, :value => @new_restaurant.coordinate.to_json %>
  <%= form.hidden_field :display_address,
    :value => @new_restaurant.display_address %>
  <%= form.submit "Submit" %>
<% end  %>